GET http://localhost:5000/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjUsIm5hbWEiOiIgYWJpIiwidXNlcm5hbWUiOiJhYmkxIiwiaWF0IjoxNzA4OTMwMzA5LCJleHAiOjE3MDg5MzAzMzl9.MPk4rNGuM_8MFJz0wG_ZqggZySjsyvcD_84_1-INe9I

###
POST http://localhost:5000/user
Content-Type: application/json

{
    "nama":" abi",
    "no_hp": "0823456965",
    "username": "abi1",
    "password": "7654",
    "id_role": "1",
    "confPassword":"7654"
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
    "username": "abi1",
    "password" : "7654"
}